export default {
	"pages": {
		"root": {
			"name": "root",
			"children": [
				"677f0d16e778710018d66496",
				"677f0d16e778710018d6649a"
			],
			"id": "root",
			"pageUrl": "root"
		},
		"677f0d16e778710018d66496": {
			"id": "677f0d16e778710018d66496",
			"name": "404",
			"pageUrl": "404"
		},
		"677f0d16e778710018d6649a": {
			"id": "677f0d16e778710018d6649a",
			"name": "index",
			"pageUrl": "index"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {
			"background": "--color-dark"
		},
		"seo": {
			"background_win10": "#232323",
			"title": "Ox1 - Tecnologia a seriço da democracia",
			"description": "Ox1 traz competências únicas em participação digital e presencial, oferecendo ferramentas que tornam processos mais transparentes e acessíveis, fortalecendo a disseminação da participação social.",
			"og:title": "Ox1 - Tecnologia a serviço da democracia, conectando cidadãos e instituições para transformar participação social.",
			"og:description": "Ox1 traz competências únicas em participação digital e presencial, oferecendo ferramentas que tornam processos mais transparentes e acessíveis, fortalecendo a disseminação da participação social.",
			"favicon_apple_152px": "https://uploads.quarkly.io/677f0d16e778710018d66478/images/blob.svg?v=2025-01-09T00:51:43.520Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/677f0d16e778710018d66478/images/blob.svg?v=2025-01-09T00:51:43.520Z",
			"og:image": "https://uploads.quarkly.io/677f0d16e778710018d66478/images/blob.svg?v=2025-01-09T00:51:43.520Z",
			"favicon_32px": "https://uploads.quarkly.io/677f0d16e778710018d66478/images/blob.svg?v=2025-01-09T00:51:43.520Z",
			"robotsFileType": "autogenerated",
			"sitemapFileType": "autogenerated",
			"customSitemapDomain": "https://ox1.pt"
		}
	}
}